import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Input from "@/components/Input/Input";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [search, setSearch] = useState("");
  const router = useRouter();

  const [windowWidth, setWindowWidth] = useState(
    typeof window !== "undefined" ? window.innerWidth : 0
  );

  useEffect(() => {
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  const handleSearch = () => {
    if (search.trim() !== "") {
      router.push(`/character?name=${search}`);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === "Enter") {
      handleSearch();
    }
  };
  const image = windowWidth < 475 ? "/logo-mobile.png" : "/logo-home.png";

  return (
    <>
      <Head>
        <title>Teste-Disney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.box}>
          <Image src={`${image}`} width={364} height={271} alt="logo" />
          <Input
            placeholder="Pesquisar"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            onKeyPress={handleKeyPress}
            onClick={handleSearch}
            icon={true}
          />
        </div>
      </div>
    </>
  );
}
