import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Input from "@/components/Input/Input";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Teste-Disney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <div className={styles.container}>
        <div className={styles.box}>
          <Image src={'/logo-home.png'} width={364} height={271} />
          <Input placeholder="Pesquisar" />
        </div>
      </div>
    </>
  );
}
